### ISSUE TITLE
inkscape 1.0.1 macos directory

### ISSUE THREAD

**Issue by fltha** [fablabnbg/inkscape-silhouette#115]
The directory for extensions on macos changed. It is now in the app-bundle itself under /Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions

But then there was this error message:
sendto_silhouette.py:126: DeprecationWarning: inkex.localize was moved to inkex.localization.localize
  inkex.localize()	# 0.91
Traceback (most recent call last):
  File "sendto_silhouette.py", line 130, in <module>
    from silhouette.Graphtec import SilhouetteCameo
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/silhouette/Graphtec.py", line 38, in <module>
    import usb1, usb.core
ModuleNotFoundError: No module named 'usb1'

**Comment by t0b3** [comment]
contains two issues

- [x] directory for OSX extensions - done with #116
- [x] port to Inkscape 1.0+ - multiple actions needed i.e.
  - [x] #90 adapt to new API
  - [x] #101 replace dropped functions
  - [x] #105 PR proposing updates for 1.0
  - [x]  #113 and others still WIP

thanks for testing on OSX and providing your feedback as we get some progress

**Comment by t0b3** [comment]
@fltha you're welcome to try the new code now and provide more feedback or open new issues...
AFAIK the macos directory issues are now resolved. see https://travis-ci.com/github/fablabnbg/inkscape-silhouette for details
